version: "3"
services:
  appointment:
    image: appointment
    container_name: appointment
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - "5050:8000"
    volumes:
      - /app/upload/:/app/upload/
    restart: always
