version: "3"
services:
  hr_mgmt:
    image: hr-mgmt
    container_name: hr-mgmt
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5050:8000"
    volumes:
      - /app/upload/:/app/upload/
    restart: always
